version: '3'

services:
  web:
    build: .
    command: gunicorn goodreads.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - media_file:/app/media-files
      - static_file:/app/static-file
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .prod.db.env
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - media_file:/app/media-files
      - static_file:/app/static-files
    depends_on:
      - web


volumes:
  media_file:
  static_file:
  postgres_data:
