version: '3'

services:
  web:
    build: .
    command: python manage.py runserver:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - media_file:/app/media-files
#      - static_file:/app/static-file
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .db.env
    ports:
      - "5432:5432"

#  nginx:
#    build: ./nginx
#    ports:
#      - "1337:80"
#    volumes:
#      - media_file:/app/media-files
#      - static_file:/app/static-file
#    depends_on:
#      - web


volumes:
  media_file:
#  static_file:
  postgres_data:
